# Generated by Django 4.1.4 on 2023-02-07 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default=None, max_length=50)),
                ('author_name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(default=None, max_length=50)),
                ('stud_password', models.CharField(default='1234', max_length=50, null=True)),
                ('stud_phno', models.BigIntegerField(default=None)),
                ('stud_semester', models.IntegerField(default=None)),
                ('stud_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryManagementApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Issue_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryManagementApp.books')),
                ('stud_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryManagementApp.student')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryManagementApp.course'),
        ),
    ]
